### ISSUE TITLE
Make tutorial 

### ISSUE THREAD

**Issue by michalss** [kboykboy2/TocPatcher#1]
Hi can you please make tutorial how to make a patch?

**Comment by kboykboy2** [comment]
read the read me

**Comment by michalss** [comment]
> read the read me

I know hoe to patch toc file. But how to make own utoc ucas pak files in general?

**Comment by michalss** [comment]
Problem is for example datatables..

**Comment by kboykboy2** [comment]
i make tool, i no make modding guide
