### ISSUE TITLE
Toc incorrect commpession block size

### ISSUE THREAD

**Issue by michalss** [kboykboy2/TocPatcher#2]
![image](https://user-images.githubusercontent.com/1000729/206874782-f8d0199d-cb28-49e1-aaa2-acd4ff21fdee.png)

Dont really get it. toc from 4.27.2. It is the same size of the block, still does not work..

**Comment by kboykboy2** [comment]
yeah got a fix for it i think, will upload soon

**Comment by kboykboy2** [comment]
alright i added a new release, let me know if it works
