### ISSUE TITLE
UE5.2 Support

### ISSUE THREAD

**Issue by Tamely** [kboykboy2/TocPatcher#4]
Hey, I just recently saw this and was wondering if you're planning on supporting UE5.2 any time soon. If you aren't, to add support myself, do I just have to copy the UE5 source into IoStore.h, or are there extra steps I'm not seeing?

**Comment by kboykboy2** [comment]
is 5.1 not the latest release?, regardless unless they change anything major, it should work for it

**Comment by Tamely** [comment]
5.1 is the lastest official release, but 5.2 is on the dev branch and it changed a lot in the file structure

**Comment by Tamely** [comment]
![Screenshot of the error when you use a toc from 5.2](https://user-images.githubusercontent.com/64652542/209720308-4a24904f-f994-4eff-b657-8022cb689e2c.png)

**Comment by Tamely** [comment]
I can send a toc if needed

**Comment by Tamely** [comment]
I also tested with UE5.1 and it's the same issue
